---
title: "Understanding and predicting\nwildfire extremes"
subtitle: "https://github.com/mbjoseph/wildfire-extremes"
author: "Maxwell B. Joseph"
date: "2018-08-07"
output:
  beamer_presentation:
    latex_engine: xelatex
    fonttheme: "structurebold"
header-includes: 
- \usepackage{graphicx}
- \beamertemplatenavigationsymbolsempty
- \usefonttheme{professionalfonts}
- \renewcommand{\familydefault}{\sfdefault}
- \usepackage{xcolor}
- \definecolor{foreground}{RGB}{0,0,0}
- \definecolor{background}{RGB}{255,255,255}
- \definecolor{title}{RGB}{0,120,255}
- \definecolor{gray}{RGB}{155,155,155}
- \definecolor{subtitle}{RGB}{204,0,204}
- \definecolor{hilight}{RGB}{102,255,204}
- \definecolor{vhilight}{RGB}{255,111,207}
- \setbeamercolor{titlelike}{fg=title}
- \setbeamercolor{subtitle}{fg=subtitle}
- \setbeamercolor{institute}{fg=gray}
- \setbeamercolor{normal text}{fg=foreground,bg=background}
- \setbeamercolor{local structure}{fg=title}
- \setbeamertemplate{frametitle}{\begin{centering} \insertframetitle \par \end{centering}}
---

```{r setup, include=FALSE}
h <- 2.2

knitr::opts_chunk$set(echo = FALSE, 
                      fig.width = 1.618 * h, fig.height = h, 
                      message = FALSE, fig.align = 'center')
library(rgeos)
library(sf)
library(tidyverse)
library(patchwork)
library(RColorBrewer)
library(splines)
theme_set(theme_minimal() + 
            theme(panel.grid.minor = element_blank()))
```

# 

```{r, echo = FALSE, results='hide', message=FALSE}
# Read fire data ----------------------
mtbs <- read_rds('../data/processed/mtbs.rds') %>%
  mutate(train = FIRE_YEAR < 2010)
mtbs %>%
  group_by(FIRE_YEAR) %>%
  summarize(max_size = max(R_ACRES)) %>%
  ggplot(aes(FIRE_YEAR, max_size)) + 
  geom_point(data = mtbs, aes(y = R_ACRES), alpha = .01) +
  geom_point() + 
  scale_y_log10() + 
  xlab('Year') + 
  ylab('Fire size (acres)')
```

# Two ideas

1. Changing size distributions
2. More ignitions $\rightarrow$ more extremes

# 

```{r, echo = FALSE}
len <- 100
density_df <- tibble(x = seq(-4, 5, length.out = len)) %>%
  mutate(old_den = dnorm(x), 
         new_den = dnorm(x, mean = 1), 
         exp_x = exp(x))

density_df %>%
  ggplot(aes(x, old_den)) + 
  geom_line(alpha = .4) + 
  theme(axis.text = element_blank(),
        panel.grid = element_blank()) +
  xlab('Fire size') + 
  ylab('Probability') + 
  geom_line(aes(y = new_den)) + 
  annotate(x = -2, y = .3, label = '1984', alpha = .4, geom = 'text', 
           size = 6) + 
  annotate(x = 3, y = .3, label = '2015', geom = 'text', 
           size = 6)
```


#

```{r, echo = FALSE}
sampling_plot <- function(n = 5, seed) {
  set.seed(seed)
  samples <- tibble(x = rnorm(n))
  p <- density_df %>%
    ggplot(aes(x, old_den)) + 
    geom_line(alpha = .4) + 
    theme(axis.text = element_blank(),
          panel.grid = element_blank()) +
    xlab('Fire size') + 
    ylab('Probability') +
    geom_vline(xintercept = max(samples$x), color = 'red') + 
    geom_rug(data = samples, inherit.aes = FALSE, aes(x), sides = 'b') + 
    ggtitle(paste('n =', n))
  p
}

seed <- 12
sampling_plot(n = 5, seed)
```

# 

```{r, echo = FALSE}
sampling_plot(n = 10, seed)
```

#

```{r, echo = FALSE}
sampling_plot(n = 20, seed)
```

#

```{r, echo = FALSE}
sampling_plot(n = 50, seed)
```

#

```{r, echo = FALSE}
sampling_plot(n = 100, seed)
```

#

```{r, echo = FALSE}
sampling_plot(n = 500, seed)
```

#

```{r, echo = FALSE}
sampling_plot(n = 1000, seed)
```

# The number of fires is stochastic

```{r, echo = FALSE}
e_nb <- 2
s_nb <- 2

num_dist <- tibble(x = 0:30) %>%
  mutate(pr_y = dnbinom(x, mu = e_nb, size = s_nb))
p2 <- num_dist %>%
    ggplot(aes(x, pr_y)) + 
    geom_point() + 
    geom_linerange(aes(ymin = 0, ymax = pr_y)) +
    theme(axis.text = element_blank(),
          panel.grid = element_blank()) +
    xlab('Number of fires') + 
    ylab('')

p2 + 
  ylab('Probability')
```

# 

```{r, echo = FALSE}
p1 <- density_df %>%
    ggplot(aes(x, old_den)) + 
    geom_line() + 
    theme(axis.text = element_blank(),
          panel.grid = element_blank()) +
    xlab('Fire size') + 
    ylab('')


arrow_df <- data.frame(x = c(0),
                       xend = c(1),
                       y = c(0), 
                       yend = c(0))

p3 <- ggplot(arrow_df, aes(x, y)) + 
  geom_segment(aes(xend = xend, yend = yend), 
               arrow = arrow()) + 
  theme_void()

n_count <- 100
count_vals <- rnbinom(n_count, mu = e_nb, size = s_nb)
p4 <- expand.grid(n = count_vals,
            x = density_df$x) %>%
  as_tibble %>%
  mutate(id = rep(1:n_count, times = nrow(density_df)), 
         max_den = n * pnorm(x)^(n - 1) * dnorm(x)) %>%
  ggplot(aes(x, max_den, group = id)) + 
  geom_line(alpha = .1) + 
  xlab('Maximum size') + 
  ylab('') + 
  theme(axis.text = element_blank(),
      panel.grid = element_blank())

(p1 + p2 + plot_layout(ncol = 1)) | p3 | p4
```

# Our approach

Relate fire size and number to:

- meteorological conditions
- housing density
- ecological context

**Can we predict extremes?**

# The data

1984-2009 (train), 2010-2015 (test)

```{r, echo = FALSE}
if (!file.exists('../data/processed/simple_ecoregions.rds')) {
  ecoregions <- read_rds('../data/processed/ecoregions.rds') %>%
    as('Spatial') %>%
    gSimplify(tol = 500) %>%
    as('sf')
}

fire_map <- ecoregions %>%
  ggplot() +
  geom_sf(size = .2, fill = 'white') + 
  geom_sf(data = mtbs, size = .1, 
          inherit.aes = FALSE, color = 'red', alpha = .2) + 
  theme_minimal() + 
  theme(panel.grid.major = element_line(colour = "lightgrey"), 
        legend.position = 'none', 
        axis.text = element_blank()) + 
  ggtitle('')

fire_map
```

# Nonlinear effects

```{r, message = FALSE, fig.width=8}
theme_set(theme_minimal() + 
            theme(panel.grid.minor = element_blank(), 
                  panel.grid.major = element_blank(), 
                  axis.text.x = element_blank(), 
                  plot.title = element_text(size=10)))

m <- 5
pal <- 2
axis_alpha <- .2

# Simulating function values ----------------------------------------------
n <- 100
x <- seq(0, 1, length.out = n)
unweighted_basis <- splines::bs(x, df = 5, intercept = TRUE) %>%
  as.data.frame() %>%
  as_tibble %>%
  mutate(x = x) %>%
  gather(key = 'dim', 'basis_value', -x) %>%
  mutate(dim = as.integer(dim), 
         weight = 1,
         type = 'Unweighted')

weights <- c(-1, 1, -.5, 1, 1)

function_val <- unweighted_basis %>%
  mutate(type = 'Weighted', 
         weight = weights[dim], 
         weighted_value = weight * basis_value) %>%
  group_by(x) %>%
  summarize(f_x = sum(weighted_value))

# TODO: replicate this for each ecoregion to show that we get clusters of functions
```