#!/bin/bash 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pr/pr_1983.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pr/pr_1984.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pr/pr_1985.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pr/pr_1986.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pr/pr_1987.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pr/pr_1988.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pr/pr_1989.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pr/pr_1990.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pr/pr_1991.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pr/pr_1992.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pr/pr_1993.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pr/pr_1994.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pr/pr_1995.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pr/pr_1996.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pr/pr_1997.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pr/pr_1998.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pr/pr_1999.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pr/pr_2000.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pr/pr_2001.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pr/pr_2002.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pr/pr_2003.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pr/pr_2004.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pr/pr_2005.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pr/pr_2006.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pr/pr_2007.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pr/pr_2008.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pr/pr_2009.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pr/pr_2010.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pr/pr_2011.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pr/pr_2012.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pr/pr_2013.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pr/pr_2014.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pr/pr_2015.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pr/pr_2016.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/tmmx/tmmx_1983.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/tmmx/tmmx_1984.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/tmmx/tmmx_1985.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/tmmx/tmmx_1986.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/tmmx/tmmx_1987.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/tmmx/tmmx_1988.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/tmmx/tmmx_1989.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/tmmx/tmmx_1990.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/tmmx/tmmx_1991.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/tmmx/tmmx_1992.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/tmmx/tmmx_1993.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/tmmx/tmmx_1994.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/tmmx/tmmx_1995.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/tmmx/tmmx_1996.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/tmmx/tmmx_1997.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/tmmx/tmmx_1998.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/tmmx/tmmx_1999.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/tmmx/tmmx_2000.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/tmmx/tmmx_2001.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/tmmx/tmmx_2002.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/tmmx/tmmx_2003.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/tmmx/tmmx_2004.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/tmmx/tmmx_2005.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/tmmx/tmmx_2006.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/tmmx/tmmx_2007.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/tmmx/tmmx_2008.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/tmmx/tmmx_2009.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/tmmx/tmmx_2010.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/tmmx/tmmx_2011.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/tmmx/tmmx_2012.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/tmmx/tmmx_2013.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/tmmx/tmmx_2014.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/tmmx/tmmx_2015.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/tmmx/tmmx_2016.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/vs/vs_1983.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/vs/vs_1984.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/vs/vs_1985.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/vs/vs_1986.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/vs/vs_1987.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/vs/vs_1988.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/vs/vs_1989.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/vs/vs_1990.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/vs/vs_1991.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/vs/vs_1992.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/vs/vs_1993.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/vs/vs_1994.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/vs/vs_1995.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/vs/vs_1996.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/vs/vs_1997.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/vs/vs_1998.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/vs/vs_1999.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/vs/vs_2000.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/vs/vs_2001.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/vs/vs_2002.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/vs/vs_2003.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/vs/vs_2004.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/vs/vs_2005.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/vs/vs_2006.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/vs/vs_2007.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/vs/vs_2008.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/vs/vs_2009.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/vs/vs_2010.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/vs/vs_2011.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/vs/vs_2012.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/vs/vs_2013.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/vs/vs_2014.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/vs/vs_2015.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/vs/vs_2016.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pdsi/pdsi_1983.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pdsi/pdsi_1984.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pdsi/pdsi_1985.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pdsi/pdsi_1986.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pdsi/pdsi_1987.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pdsi/pdsi_1988.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pdsi/pdsi_1989.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pdsi/pdsi_1990.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pdsi/pdsi_1991.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pdsi/pdsi_1992.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pdsi/pdsi_1993.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pdsi/pdsi_1994.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pdsi/pdsi_1995.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pdsi/pdsi_1996.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pdsi/pdsi_1997.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pdsi/pdsi_1998.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pdsi/pdsi_1999.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pdsi/pdsi_2000.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pdsi/pdsi_2001.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pdsi/pdsi_2002.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pdsi/pdsi_2003.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pdsi/pdsi_2004.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pdsi/pdsi_2005.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pdsi/pdsi_2006.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pdsi/pdsi_2007.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pdsi/pdsi_2008.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pdsi/pdsi_2009.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pdsi/pdsi_2010.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pdsi/pdsi_2011.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pdsi/pdsi_2012.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pdsi/pdsi_2013.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pdsi/pdsi_2014.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pdsi/pdsi_2015.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pdsi/pdsi_2016.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pet/pet_1983.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pet/pet_1984.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pet/pet_1985.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pet/pet_1986.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pet/pet_1987.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pet/pet_1988.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pet/pet_1989.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pet/pet_1990.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pet/pet_1991.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pet/pet_1992.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pet/pet_1993.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pet/pet_1994.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pet/pet_1995.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pet/pet_1996.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pet/pet_1997.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pet/pet_1998.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pet/pet_1999.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pet/pet_2000.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pet/pet_2001.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pet/pet_2002.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pet/pet_2003.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pet/pet_2004.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pet/pet_2005.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pet/pet_2006.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pet/pet_2007.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pet/pet_2008.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pet/pet_2009.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pet/pet_2010.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pet/pet_2011.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pet/pet_2012.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pet/pet_2013.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pet/pet_2014.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pet/pet_2015.nc 
wget -nc -c -nd http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/pet/pet_2016.nc 
